import type { Data } from "./types";

export const data: Data[] = [
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },
  {
    date: '24.06',
    fio: 'Зубенко Михаил Петрович',
    object_name: 'Склад',
    phone: '+79999999999',
    email: 'zubenko@gmail.com',
    serial_numbers: ['ER414260001'],
    device_type: 'Встроенные',
    sentiment: 'Нейтральный',
    answer: 'Как починить',
  },  
];